apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: java-app
        image: mb938/demo-app:java-app
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: mysql-user-username
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: mysql-user-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: database_name
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: java-app-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080