appName: java-app
appImage: mb938/demo-app:java-app
appReplicas: 2
containerPort: 8080
imagePullSecrets:
- my-registry-key
containerEnvVars:
- name: DB_USER
  value: "mohamed"
- name: DB_PWD
  valueFrom:
    secretKeyRef:
      name: mysqldb
      key: mysql-password
- name: DB_NAME
  value: "my_database"
- name: DB_SERVER
  valueFrom:
    configMapKeyRef:
      name: java-app-configmap
      key: database_url

servicePort: 8080
serviceType: ClusterIP

configMap:
  enabled: true
  name: java-app-configmap
  data:
  - key: database_url
    value: "mysqldb-primary"

secret:
  enabled: false

ingress:
  enabled: true
  name: java-app
  className: nginx
  host: <nodebalancer-hostname>
  paths:
  - path: /
    pathType: Prefix
    serviceName: java-app
    servicePort: 8080
