releases:
  - name: java-app
    chart: charts/my-chart
    values:
      - values/java-application-values.yaml

  - name: phpmyadmin
    chart: charts/my-chart
    values:
      - values/phpmyadmin-values.yaml
