global:
  security:
    allowInsecureImages: true
architecture: replication
auth:
  createDatabase: true
  database: "my_database"
  username: "mohamed"
volumePermissions:
  enabled: false
primary:
  persistence:
    storageClass: "linode-block-storage"
    size: 8Gi
secondary:
  replicaCount: 1
  persistence:
    storageClass: "linode-block-storage"
    size: 8Gi
image:
  registry: docker.io
  tag: latest
  repository: bitnamilegacy/mysql
